### ISSUE TITLE
Python SDK has complex way of API key upload

### ISSUE THREAD

**Issue by nekrkris** [oracle/oci-python-sdk#119]
1. In the doc https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/identity/models/oci.identity.models.ApiKey.html#oci.identity.models.ApiKey you can see "UNKNOWN_ENUM_VALUE".. that needs to be corrected. Not sure when that can happen.

2. Once I use the upload_api_key in IdentityClient to upload a public key. Its very difficult to know when the lifecycle state changes to ACTIVE.

3. No examples to use this API

https://github.com/oracle/oci-python-sdk/blob/master/docs/api/identity/models/oci.identity.models.ApiKey.rst
or

4. Further more the problem is the format of the public API key ... I had to do something like this:
POLICY_TEST_USER_PUBLIC_KEY_LINES = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3wcQOvxpNDizIAzwDfas\nFfWQRRtVfZ31wNosly30e811iZ8NNF7f6OoZww8e/j9ezxkKXlTVGsD+75iaTaZ3\nPbdOywqdLtyOEpRlnqOBVoeK8nWxEWKXyrnmWyolE01zkxNWVk5jI75LaNaMVMa2\nWXjkAEtn/M5+wBY+MELT9UZVXhFohZ1vLexvJwe1W1r0Mu4n9Z7ujuFaZqD/osQe\nAF57fq7SOGu4An/z4qE+oGiJJGPnQPDKEXJCfjUIIeFkOBH8RyMhQrPbSGp7/lBv\nvtbl0PuOB3fUOtDmW84+1ZpHgON9jBGoHyinfS06Dn0YH5VBoL1xpjvAea2PIWOq\nuQIDAQAB\n-----END PUBLIC KEY-----"

It should have accepted in the base64 format and not in this format

**Comment by arthall** [comment]
Hi @nekrkris, thank you for your feedback.  I won't be able to address everything that you bring up here because some of your suggestions require changing the API which is larger in scope than a single SDK.

1.  UNKNOWN_ENUM_VALUE is a forward compatibility value to handle the service updating their enum values.  That way the SDK does not require an update if the service later adds a value to the enum that the SDK doesn't know about.  From the page you linked

```
Any unrecognized values returned by a service will be mapped to 'UNKNOWN_ENUM_VALUE'.
```

2. Yes, having a corresponding get_api_key would simplify checking the lifecycle state.  Then you could use a waiter to wait for the key to become active.  API changes have a larger scope than a specific SDK and will need to be discussed and coordinated with partner teams.

3. I don't see a Python SDK specific example.   I'll ask around to see if someone has a Python SDK specific example that can be added.  If there was one it would be here: https://github.com/oracle/oci-python-sdk/tree/master/examples.  The RST file you link to is generated from the code and is a stub for Sphinx.  That RST becomes the HTML in the first link you provided.  There are more docs on uploading API keys here: https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingcredentials.htm#upload_key and https://docs.cloud.oracle.com/iaas/api/#/en/identity/20160918/ApiKey/UploadApiKey

4.  In the docs you linked key_value is defined as having type str.  Why do you assume the value should be base64 encoded?  Are there docs that indicates base64?  If there are, we need to correct them.

**Comment by arthall** [comment]
@nekrkris, there is an example now.  https://github.com/oracle/oci-python-sdk/blob/master/examples/add_API_key.py.  Thank you for your help.

**Comment by arthall** [comment]
I'm closing this ticket, since an example has been added and the API changes are beyond the scope of the SDK.
