### ISSUE TITLE
Anyone having issues with running this for the new Zurich region?

### ISSUE THREAD

**Issue by alxfirst** [oracle/oci-python-sdk#153]
This is throwing an error for a tenancy that has resources in the new zurich region. Has anyone else experienced this?

Error in ShowOCIService:__load_data_main: : HTTPSConnectionPool(host='email.eu-zurich-1.oraclecloud.com', port=443): Max retries exceeded with url: /20170907/senders?compartmentId=**xxx**&sortBy=EMAILADDRESS (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0550d13d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
socket.gaierror: [Errno -2] Name or service not known
oci._vendor.urllib3.exceptions.NewConnectionError: <oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0550d13d30>: Failed to establish a new connection: [Errno -2] Name or service not known

**Comment by adizohar** [comment]
Hi Alxfirst
It has been fixed with the new version coming tomorrow
Handling exception of service not yet available at the request level.
For your info
Adi.

**Comment by ghofweber** [comment]
FYI I've used your latest version


In general it works well I think


But also get following errors in nohup.out




Remember it's taking 13 tenants


   Completed With 36x(Service Warnings) 1 (Processing


Errors)  at 2019-08-31 23:06:26   #


rror in ShowOCIData:__get_core_compute_instance_confi


uration: must be str, not int


   Completed With 26x(Service Warnings) 1 (Processing


Errors)  at 2019-09-01 10:56:22   #


rror in ShowOCIData:__get_core_compute_instance_confi


uration: must be str, not int


   Completed With 36x(Service Warnings) 1 (Processing


Errors)  at 2019-09-01 23:04:50   #


rror in ShowOCIData:__get_core_compute_instance_confi


uration: must be str, not int


   Completed With 18x(Service Warnings) 1 (Processing


Errors)  at 2019-09-02 10:55:12   #




 


 


 


 






On Mon, Sep 2, 2019 at 3:04 PM +0200, "Adi Zohar" <notifications@github.com> wrote:












Hi Alxfirst

It has been fixed with the new version coming tomorrow

Handling exception of service not yet available at the request level.

For your info

Adi.

**Comment by adizohar** [comment]
Hi thank you for the feedback, I will check the "ShowOCIData:__get_core_compute_instance_confiuration: must be str, not int" and will fix as well
Appreciate it

**Comment by adizohar** [comment]
I fixed it and it will be there for next release - next week
if you want to add the code , in showoci_services,py, ~ line 3272 , function __load_core_compute_inst_config:

Add the STR function for the below:
                                    if instance_detail.block_volumes:
                                        val['block_volumes'] = **str**(len(instance_detail.block_volumes))
                                    if instance_detail.secondary_vnics:
                                        val['secondary_vnics'] = **str**(len(instance_detail.secondary_vnics))

**Comment by adizohar** [comment]
Alxfirst, code as been released, can you please check and let me know ? 
Thank you

**Comment by jodoglevy** [comment]
Fix has been deployed - closing this. If its not working let us know and we'll reopen.
