### ISSUE TITLE
Python 3 throwing error on oci.pagination.list_call_get_all_results(identity.list_region_subscriptions, tenancy)

### ISSUE THREAD

**Issue by rwuebker** [oracle/oci-python-sdk#157]
Hello,

I'm having this issue using python 3.6.8 and oci 2.3.3: 

1. I have a config file that has six fields (this is a python dictionary) and the values are all strings in Python 3. 

2. I create an `oci.identity.IdentityClient` with this config. This works fine.

3. Next I run `oci.pagination.list_call_get_all_results(my_identity.list_region_subscriptions, config['tenancy'])` where tenancy is also a string. This returns an error: `'str' object has no attribute 'decode'`. I tried changing the tenancy string to a byte object, and I tried changing the values in the config to byte objects, but if I do that I get an error that says: `cannot perform str operations on a byte`.

Have you seen this before?

Thanks,
Rick

**Comment by arthall** [comment]
I'm not able to reproduce the issue you are seeing with the information given.  I do get errors, but they aren't the same as the ones you are seeing.

In item 2, do you mean `oci.identity.IdentityClient` and are the results of that assigned to `my_identity`?

In item 3, the pagination functions take a function as the first parameter, but it looks like you are passing an IdentityClient object.  Which identity list function are you wanting to call?

Please run this example and let me know if it works for you.  You may need to create the config dictionary programmatically rather than reading it in from a file and you may need to substitute `config['tenancy']` with a compartment id depending on you have things configured.

```
import oci
# This reads the config from a file, but it's ok to create a the config as a dictionary
config = oci.config.from_file()
my_identity = oci.identity.IdentityClient(config)
# My tenancy is in my config, but any valid compartment id will work on the next line
response = oci.pagination.list_call_get_all_results(my_identity.list_compartments, config['tenancy'])
for compartment in response.data:
    print(compartment)
```

**Comment by rwuebker** [comment]
Thanks for the response. I edited my previous post. Yes I'm using IdentityClient and passing in the function my_identity.list_region_subscriptions as the first arg and config['tenancy'] as the second arg. 

I do create the config programmatically after it reads it from a file. I'll give your suggestion a try and report back. Thanks.

**Comment by rwuebker** [comment]
Looks like I had something upstream that was causing a problem unrelated to the oci sdk so I'm closing this issue. Thank you for taking a look!
