### ISSUE TITLE
Outdated requirements.txt

### ISSUE THREAD

**Issue by j4v** [oracle/oci-python-sdk#254]
The cryptography dependency (https://github.com/oracle/oci-python-sdk/blob/master/requirements.txt#L5) is set to 2.8, which is outdated (https://pypi.org/project/cryptography/#history). Is there a reason to set the dependency to this specific reason, or can it be upgraded?

This is causing us issues https://github.com/nccgroup/ScoutSuite/issues/736 as up to date systems will have a newer version of the dependency.

**Comment by j4v** [comment]
@jodoglevy any ETA on this?

**Comment by bhagwatvyas** [comment]
Hi @j4v, the reason that the cryptography dependency is set to v2.8 is we have tested with, and have compliance and security approval to use v2.8. 

The mentioned issue seems like a version conflict between the version that comes with Debian, and what the OCI Python SDK requires. Could you confirm if they are using the OCI Python SDK within a virtual environment?

**Comment by j4v** [comment]
> Could you confirm if they are using the OCI Python SDK within a virtual environment?

Just had another look at https://github.com/nccgroup/ScoutSuite/issues/736, they where indeed not using a virtualenv. This is only an issue when installing the dependencies directly on the host system (in our case in a container).

**Comment by bhagwatvyas** [comment]
The recommended way to use the Python SDK is within a virtual environment (https://github.com/oracle/oci-python-sdk#installation). This will resolve the problem of incompatible dependencies between the operating system and the Python SDK. Since it seems like virtual environment should solve this issue, I’m closing this ticket, but feel free to reopen if there is still an issue to be resolved.
