### ISSUE TITLE
Document build instructions

### ISSUE THREAD

**Issue by brunoborges** [oracle/oci-python-sdk#26]
Is it possible to have build instructions documented somewhere?

**Comment by nathan-vu** [comment]
Hi Bruno,

Could you expand the kind of instructions you're looking for here. For example, is it:

* Instructions on how to build the wheel for the SDK
* A more explicit developer section of the README on how to get started developing on the SDK, running tests, generating docs etc.
* Scripts which could be used to do the build and run tests, e.g. so that they could be hooked into a CI system like Travis

Or something else?

Thanks,
Nathan

**Comment by brunoborges** [comment]
Well, we could start with a section in the readme with the build instructions.

**Comment by brunoborges** [comment]
Something that answers the question "how do I build this project locally?"

**Comment by nathan-vu** [comment]
Sorry for the delayed update here. I've got some changes to the README to include a Development section that describes how to get started, run tests and do builds. That should be out with our next push

**Comment by nathan-vu** [comment]
v1.3.7 has been released and the README now contains the development section mentioned in my previous comment (https://github.com/oracle/oci-python-sdk#development)
