### ISSUE TITLE
oci.encryption.KMSMasterKeyProvider does not support auth_type=instance_principal

### ISSUE THREAD

**Issue by CowboyNick** [oracle/oci-python-sdk#313]
When attempting to execute the example python code using oci.encryption.KMSMasterKey and oci.encryption.KMSMasterKeyProvider, the signer  and identity client do not appear to be supported. It only works by passing in a config or with config.from_file(). 

Example Code:

```
from oci import auth, identity, encryption


signer = auth.signers.InstancePrincipalsSecurityTokenSigner()
identity_client = identity.IdentityClient(config={}, signer=signer)

# user supplied vars
vault_id = '<VAULT_OCID>'
master_key_id = '<MASTER_KEY_OCID>'
data_to_encrypt_bytes = b"This is a secret message"

kms_master_key = encryption.KMSMasterKey(
    master_key_id=master_key_id, vault_id=vault_id,
    signer=signer
)

kms_master_key_provider = encryption.KMSMasterKeyProvider(
    signer=signer,
    kms_master_keys=[kms_master_key]
)

crypto_result = encryption.encrypt(kms_master_key_provider, data_to_encrypt_bytes)
ciphertext = crypto_result.get_data()
print("ciphertext: {}".format(ciphertext))

# decrypt string example
crypto_result = encryption.decrypt(ciphertext, kms_master_key_provider)
print("unencrypted text: {}".format(crypto_result.get_data()))
```

Error message:
```
[opc@testinst1 ~]$ python test.py
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    signer=signer
TypeError: __init__() got an unexpected keyword argument 'signer'
```

**Comment by adizohar** [comment]
Hi CowboyNick

In order to encrypt and decrypt using OCI KMS you need to use the KMS Client not encryption library

Please check the example - https://github.com/oracle/oci-python-sdk/blob/master/examples/kms_example.py
Documentation = https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/key_management/client/oci.key_management.KmsCryptoClient.html#oci.key_management.KmsCryptoClient

For your info

**Comment by CowboyNick** [comment]
Hi Adi, I was able to get this to work using the KMS example. Thanks.
