### ISSUE TITLE
Possible to override this check?

### ISSUE THREAD

**Issue by sdstewar** [oracle/oci-python-sdk#334]
https://github.com/oracle/oci-python-sdk/blob/16b608e14836b334883d8ba9aee2e67216c5399e/src/oci/config.py#L119

I recently updated some automation to use the latest SDK and ran into a problem with this added check.  In my case the code is running inside a container with config directory mapped from the host.  In the past I check for the existence of the mapped volume and then simply rewrote the `key_file` value returned from `from_file(...)` to correct the volume mapping in the container but this now prevents that.  

Would it be possible to add a flag to bypass this check and restore this ability or do I have to parse the config file myself to make it a bit more portable.

**Comment by bhagwatvyas** [comment]
Hey @sdstewar I'd suggest you to read the config file yourself, build a config dictionary and pass it to the client, as demonstrated in the docs here https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/configuration.html.

Since this is a very rare case and there is a simple workaround, we would prefer not to take this request at this time. Please let me know if you have any questions/concerns.

**Comment by KartikShrikantHegde** [comment]
Hi @sdstewar ,

I will be closing this issue based on the workaround and @bhagwatvyas response. Please feel free to reopen if required.

Thanks.
