### ISSUE TITLE
in oci.usage_api.UsageapiClient, many retrieved values are none

### ISSUE THREAD

**Issue by kk-hiraskar** [oracle/oci-python-sdk#380]
```py
usgCl = oci.usage_api.UsageapiClient(config)
reqObj = oci.usage_api.models.RequestSummarizedUsagesDetails(tenant_id=tenancyOcid, 
        granularity='MONTHLY', query_type='USAGE', 
        #group_by=['compartmentName'], compartment_depth=5,
        time_usage_started=datetime(2021,7,1,0,0), time_usage_ended=datetime(2021,8,26,0,0))
usgSumm = usgCl.request_summarized_usages(reqObj)

for usg in usgSumm.data.items:
   ... ...
```

with this execution, only few output values are visible, and all other values I am getting as `None`  
> _unit, computed_quantity, computed_amount, currency, time_usage_started, time_usage_ended_

getting as `None` for
> _compartment_name, compartment_path, region, ad, resource_name, service, shape_

compartment values not getting even after group_by is applied.

### Is I am doing anything wrong here?, plz suggest

and one more thing observed, on applying group_by, `currency` value also becoming None

**Comment by kk-hiraskar** [comment]
If there can be done any interim changes in local copy of modules to get compartment names, kindly let me know.

**Comment by adizohar** [comment]
HI KK-Hiraskar

Some info about the usage API below:

## How to use Granularity?
We support MONTLY, DAILY, HOURLY
All startTime is inclusive and endTime is exclusive same as Java substring. 
For HOURLY, it only support max 36 hour time period and no more precision than hour. It means no minutes or second in the input time.
For MONTLY, it only support 1st date of the month to another 1st date of the month. eg: 2020-06-01T00:00:00Z,  max 12 months period.
For DAILY, no more precision than day. You must input as 00:00:00 eg: 2020-06-01T00:00:00Z . Max 90 days period.  

## How to use groupBy?
In API response, it only show the dimension in groupBy. eg: If "service" isn't in groupBy, "service" field in response will be empty. 
If groupBy list is empty, "currency" will be add into groupBy
If queryType is Usage, "unit" will be add into groupBy.
If queryType is COST or empty, "currency" will be add into groupBy
"computedAmount" work as expect only when "currency" is in groupBy.
"computedQuality"  work as expect only when "unit" is in groupBy.

## What is QueryType?
The API can query USAGE or COST. computedQuality represent usage and computedAmount represent cost. For getting expected usage, you need to set queryType to USAGE or add "unit" in groupByKey. It is because usage is aggregated/grouped correctly when group by unit. 

## How to groupBy compartment?
GroupBy compartment related keys ("compartmentName", "compartmentPath", "compartmentId")is different with the other groupBy keys.

For getting expected result, you must request with compartmentDepth. compartmentDepth is >=1 and <=6. 

GroupBy compartment means all usage/cost of compartments with higher depth will be aggregated to the compartment with given depth. 

If depth is 1, it means all usage/cost grouped to root compartment.
If depth is 2, it means all compartments with depth 2 will contain the usage/cost with all its children. In response, root will contain its own usage, B will aggregate (B, D, E, F), C will contain C.

## Why are some fields in response empty?
The fields will show up only when the fields in groupBy. Not all fields in response are available now

## example:

```
import oci

config_file="~/.oci/config"
config = oci.config.from_file(config_file,"DEFAULT")

usageapiClient = oci.usage_api.UsageapiClient(config)
requestSummarizedUsagesDetails = oci.usage_api.models.RequestSummarizedUsagesDetails(
    tenant_id=config['tenancy'],
    granularity='MONTHLY',
    query_type='USAGE',
    group_by=['compartmentName','compartmentPath'],
    compartment_depth=5,
    time_usage_started='2020-07-01T00:00:00.000Z',
    time_usage_ended='2020-08-01T00:00:00.000Z'
)
request_summarized_usages = usageapiClient.request_summarized_usages(requestSummarizedUsagesDetails)
print(request_summarized_usages.data)
```

**Comment by kk-hiraskar** [comment]
Thanks @adizohar 
this details is very much clear.
