### ISSUE TITLE
Include routing_policy in CreateLoadBalancerDetails

### ISSUE THREAD

**Issue by sauravmistry1989** [oracle/oci-python-sdk#428]
Please include routing_policy in CreateLoadBalancerDetails.

**Comment by sauravmistry1989** [comment]
Hello Team,

Any update on it ?

**Comment by sauravmistry1989** [comment]
Hello Team,

Is there timeline when we can expect this enhancement ?

**Comment by KartikShrikantHegde** [comment]
Hi @sauravmistry1989 , 

There is an api for Routing Policy - https://docs.oracle.com/en-us/iaas/api/#/en/loadbalancer/20170115/RoutingPolicy/CreateRoutingPolicy

If you want to attach Routing Policy to LB, then you can follow the above document for any SDK. We didn't have Routing Policy header functionality in CreateLoad BalancerDetails as we have separate API resources. 

Hope this works, let us know otherwise.

**Comment by KartikShrikantHegde** [comment]
Hi @sauravmistry1989 , I am closing this ticket, please feel free to re-open it if you still face the issue. Thanks.
