### ISSUE TITLE
Cost Analysis with Python SDK

### ISSUE THREAD

**Issue by NKMatha** [oracle/oci-python-sdk#511]
Hi team,
I was trying to get the compartment/instance cost analysis using Python SDK. I have gone through all the documentations but could not found any.
can someone please let me know with which function i can get those...

Thanks in advance

**Comment by adizohar** [comment]
Hi, You can check the code - https://github.com/oracle/oci-python-sdk/tree/master/examples/showusage
It shows example how to use the usage api

You can groupby with below keys:
"tagNamespace", "tagKey", "tagValue", "service", "skuName", "skuPartNumber", "unit",
"compartmentName", "compartmentPath", "compartmentId", "platform", "region", "logicalAd",
"resourceId", "tenantId", "tenantName"

Let me know if this help, for instance I would use resourceid

**Comment by adizohar** [comment]
Hi NKMatha

Did the above answer your query or you need additional assistance ?

**Comment by NKMatha** [comment]
Hi @adizohar thanks for your quick response and apolize me for delay.
This works good, but am looking to get cost & usage compartment wise for individual instance.

If there any further code or suggessions please provide, that would be realy greatful.

**Comment by adizohar** [comment]
Hi, below code for cost and usage per resource and compartment,
you cannot combine cost and usage because those aggregated

`
import oci
config = oci.config.from_file("~/.oci/config", "DEFAULT")
tenant_id = config['tenancy']
time_usage_started = "2023-02-04T00:00:00Z"
time_usage_ended = "2023-02-05T00:00:00Z"

print("Tenant Name  : " + str(tenant_id))

usage_client = oci.usage_api.UsageapiClient(config)

requestSummarizedUsagesDetails = oci.usage_api.models.RequestSummarizedUsagesDetails(
    tenant_id=tenant_id,
    granularity='DAILY',
    query_type='COST',
    group_by=['compartmentPath', 'resourceId', 'skuName', 'skuPartNumber'],
    time_usage_started=time_usage_started,
    time_usage_ended=time_usage_ended,
    compartment_depth=2
)

# usageClient.request_summarized_usages
request_summarized_usages = usage_client.request_summarized_usages(
    requestSummarizedUsagesDetails,
    retry_strategy=oci.retry.DEFAULT_RETRY_STRATEGY
)

print("##############################################################################")
print("#                                 Cost                                       #")
print("##############################################################################")
for item in request_summarized_usages.data.items:
    print(
        str(item.time_usage_started) +
        ", " + str(item.time_usage_ended) +
        ", " + str(item.compartment_path) +
        ", " + str(item.resource_id) +
        ", " + str(item.sku_part_number) +
        ", " + str(item.sku_name) +
        ", " + str(item.computed_amount)
    )

# request quantity

requestSummarizedUsagesDetails = oci.usage_api.models.RequestSummarizedUsagesDetails(
    tenant_id=tenant_id,
    granularity='DAILY',
    query_type='USAGE',
    group_by=['compartmentPath', 'resourceId', 'skuName', 'skuPartNumber'],
    time_usage_started=time_usage_started,
    time_usage_ended=time_usage_ended,
    compartment_depth=2
)

# usageClient.request_summarized_usages
request_summarized_usages = usage_client.request_summarized_usages(
    requestSummarizedUsagesDetails,
    retry_strategy=oci.retry.DEFAULT_RETRY_STRATEGY
)

print("##############################################################################")
print("#                                 USAGE                                      #")
print("##############################################################################")

for item in request_summarized_usages.data.items:
    print(
        str(item.time_usage_started) +
        ", " + str(item.time_usage_ended) +
        ", " + str(item.compartment_path) +
        ", " + str(item.resource_id) +
        ", " + str(item.sku_part_number) +
        ", " + str(item.sku_name) +
        ", " + str(item.computed_quantity)
    )

`

Please let me know if this work, you want to check as well the usage2adw tool which gives more options under the example page - https://github.com/oracle/oci-python-sdk/tree/master/examples/usage_reports_to_adw

**Comment by NKMatha** [comment]
Thanks @adizohar, thats realy helaps me a lot

**Comment by adizohar** [comment]
This is great, if you require additional help, please let me know , if not, can you kindly close the ticket.

**Comment by NKMatha** [comment]
hi @adizohar , I need the cost and usage analysis using the name tags, is it possible, can you to help me in this aspect? Is there any code that could be helpful. Thanks

**Comment by adizohar** [comment]
Hi, Here code to run cost per tag

```
import oci
config = oci.config.from_file("~/.oci/config", "DEFAULT")
tenant_id = config['tenancy']
time_usage_started = "2023-02-04T00:00:00Z"
time_usage_ended = "2023-02-05T00:00:00Z"

print("Tenant Name  : " + str(tenant_id))

usage_client = oci.usage_api.UsageapiClient(config)

requestSummarizedUsagesDetails = oci.usage_api.models.RequestSummarizedUsagesDetails(
    tenant_id=tenant_id,
    granularity='DAILY',
    query_type='COST',
    group_by=['tagNamespace', 'tagKey', 'tagValue', 'skuName'],
    time_usage_started=time_usage_started,
    time_usage_ended=time_usage_ended
)

# usageClient.request_summarized_usages
request_summarized_usages = usage_client.request_summarized_usages(
    requestSummarizedUsagesDetails,
    retry_strategy=oci.retry.DEFAULT_RETRY_STRATEGY
)

print("##############################################################################")
print("#                            Cost per Tag                                    #")
print("##############################################################################")
for item in request_summarized_usages.data.items:
    print(
        str(item.time_usage_started) +
        ", " + str(item.time_usage_ended) +
        ", " + str(item.tags) +
        ", " + str(item.sku_name) +
        ", " + str(item.computed_amount)
    )

```

**Comment by adizohar** [comment]
Please bear in mind, the usapeapi produce aggregated summary, same you can do on the OCI Cost Analysis console.
