### ISSUE TITLE
Is there API call to audit user login/logout info.

### ISSUE THREAD

**Issue by vipmike007** [oracle/oci-python-sdk#84]
Hi, 
Referring to $subject.Is there is API call to audit user login/logout info？
I checked the https://github.com/oracle/oci-python-sdk/blob/master/examples/retrieve_audit_events.py ,the output of events are are related to user operations based on compartment.
I walk through https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/search.html?q=login&check_keywords=yes&area=default but no luck to find one.

So Is there a API function to get all user login/logout info based on tenancy?

Thanks in advance,
Mike

**Comment by arthall** [comment]
I believe you have to iterate over the compartments to get all of the events for a tenancy.  You can use list_compartments in the identity client to get all of the compartments for the tenancy.

**Comment by arthall** [comment]
Reopening the ticket to give the service team an opportunity to comment.

**Comment by vipmike007** [comment]
@arthall  I did iterate over the compartments to get all of the events for a tenancy. there are only modify,post,add,delete operations based on comparments. there is no login/loginout events here

**Comment by manjushp** [comment]
Agreed. I changed the system root password on one of my test instances and searched for the change in the audit logs

**Comment by girinag** [comment]
- Login events from the webconsole are audited with events 'InteractiveLogin' for successful logins from native OCI users and 'FederatedInteractiveLoginAttempt' for requests that get redirected to an external Identity Provider for authentication (for federated users).
- Logout events are not audited.  It is a client-only action of clearing the session.
- There is no API to cause a 'login' or a 'logout' event since SDK access has no concept of client sessions
- Please refer to https://docs.cloud.oracle.com/iaas/Content/Audit/Tasks/viewinglogevents.htm for viewing event logs or using the ListEvents API to enumerate logs: https://docs.cloud.oracle.com/api/#/en/audit/20160918/AuditEvent/ListEvents
- ListEvents API allows filtering events based on startTime and endTime and you can filter it further on the client if you want events with a specific event name.

**Comment by arthall** [comment]
There hasn't been any activity on this ticket in months and @girinag explained how to get the get the login audit logs and why there aren't any logout events.  Please reopen the ticket if there are unaddressed concerns.
